# Generated by Django 6.1.1 on 2026-09-13 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_tag_ticket_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("actor_session_id", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "from_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("to_status", models.CharField(blank=True, max_length=100, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="tracker.ticket",
                    ),
                ),
            ],
        ),
    ]
