# Generated by Django 6.1.1 on 2026-09-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_timelineentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="linear_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
