# Generated by Django 6.1.1 on 2026-09-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_ticket_linear_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_builtin", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
