# Generated by Django 6.1.1 on 2026-09-13 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_seed_builtin_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="tracker.status",
            ),
        ),
    ]
