# Generated by Django 6.1.1 on 2026-09-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="needs_human_eyes",
            field=models.BooleanField(default=False),
        ),
    ]
