# Generated by Django 6.1.1 on 2026-09-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_ticket_needs_human_eyes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("status_change", "Status Change"),
                    ("flag_change", "Flag Change"),
                    ("field_change", "Field Change"),
                ],
                max_length=20,
            ),
        ),
    ]
