# Generated by Django 6.1.1 on 2026-09-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_timelineentry_kind_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timelineentry",
            options={"ordering": ["created_at", "id"]},
        ),
    ]
