# Generated by Django 6.1.1 on 2026-09-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_timelineentry_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
