# Generated by Django 6.1.1 on 2026-09-16 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_session_name_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="tracker.ticket",
            ),
        ),
    ]
