# Generated by Django 6.1.1 on 2026-09-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_ticket_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="tracker.ticket",
            ),
        ),
    ]
