# Generated by Django 6.1.1 on 2026-09-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="linear_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="linear_identifier",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="CronRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("api", "Api"), ("command", "Command")], max_length=20
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
    
        migrations.AddField(
            model_name="session",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("ticket_brief", "Ticket Brief"),
                    ("pr_triage", "Pr Triage"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="effort",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("running", "Running"),
                    ("finished", "Finished"),
                    ("failed", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="result_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="cron_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="tracker.cronrun",
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new_ticket", "New Ticket"),
                            ("pr_triaged", "Pr Triaged"),
                            ("pr_unlinked", "Pr Unlinked"),
                            ("cron_error", "Cron Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cron_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tracker.cronrun",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="tracker.session",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tracker.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TicketBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("md_path", models.TextField()),
                ("html_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="briefs",
                        to="tracker.session",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brief",
                        to="tracker.ticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("url", models.TextField()),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                ("branch", models.CharField(blank=True, default="", max_length=255)),
                ("head_sha", models.CharField(blank=True, default="", max_length=64)),
                ("state", models.CharField(max_length=20)),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_triage_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triaged_pull_requests",
                        to="tracker.session",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pull_requests",
                        to="tracker.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["repo", "-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repo", "number"), name="unique_pull_request"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PRComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("review_comment", "Review Comment"),
                            ("issue_comment", "Issue Comment"),
                            ("review", "Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("github_id", models.BigIntegerField()),
                ("in_reply_to_id", models.BigIntegerField(blank=True, null=True)),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("is_bot", models.BooleanField(default=False)),
                ("body", models.TextField(blank=True, default="")),
                ("path", models.TextField(blank=True, default="")),
                ("line", models.IntegerField(blank=True, null=True)),
                ("url", models.TextField(blank=True, default="")),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tracker.pullrequest",
                    ),
                ),
                (
                    "triaged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triaged_comments",
                        to="tracker.session",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pull_request", "kind", "github_id"),
                        name="unique_pr_comment",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="taskhistoryentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("state_change", "State Change"),
                    ("field_change", "Field Change"),
                    ("created", "Created"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="pull_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="tracker.pullrequest",
            ),
        ),
    ]
