/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["tracker_api_tickets_list_tickets"];
        put?: never;
        /** Create Ticket */
        post: operations["tracker_api_tickets_create_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tickets Summary */
        get: operations["tracker_api_tickets_tickets_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["tracker_api_tickets_get_ticket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Ticket */
        patch: operations["tracker_api_tickets_patch_ticket"];
        trace?: never;
    };
    "/api/tickets/{ticket_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Status */
        post: operations["tracker_api_tickets_set_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Comment */
        post: operations["tracker_api_tickets_add_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/needs-human-eyes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Needs Human Eyes */
        post: operations["tracker_api_tickets_set_needs_human_eyes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description A ticket's tasks, oldest first; the same rows as ``TicketDetail.tasks``.
         */
        get: operations["tracker_api_tickets_list_tasks"];
        put?: never;
        /** Create Task */
        post: operations["tracker_api_tickets_create_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Register Session
         * @description Idempotent upsert (A10). ``name`` is generated once, on first registration.
         */
        put: operations["tracker_api_sessions_register_session"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["tracker_api_sessions_list_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Statuses */
        get: operations["tracker_api_statuses_list_statuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["tracker_api_tasks_get_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Task */
        patch: operations["tracker_api_tasks_patch_task"];
        trace?: never;
    };
    "/api/tasks/{task_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set State */
        post: operations["tracker_api_tasks_set_state"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Actor */
        Actor: {
            /** Session Id */
            session_id: string;
            /** Name */
            name: string;
            /** Directory */
            directory: string | null;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "urgent" | "high" | "medium" | "low" | "none";
        /** Task */
        Task: {
            /** Id */
            id: number;
            /** Ticket Id */
            ticket_id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            state: components["schemas"]["TaskState"];
            /** Depends On */
            depends_on: number[];
            /** Blocked By */
            blocked_by: number[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskState
         * @enum {string}
         */
        TaskState: "todo" | "in_progress" | "done" | "cancelled";
        /** TicketDetail */
        TicketDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            priority: components["schemas"]["Priority"];
            /** Status */
            status: string | null;
            /** Needs Human Eyes */
            needs_human_eyes: boolean;
            /** Linear Url */
            linear_url: string | null;
            /** Project */
            project: string | null;
            /** Labels */
            labels: string[];
            /** Parent Id */
            parent_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Description */
            description: string;
            parent: components["schemas"]["TicketRef"] | null;
            /** Children */
            children: components["schemas"]["TicketListItem"][];
            /** Tasks */
            tasks: components["schemas"]["Task"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineEntry"][];
        };
        /** TicketListItem */
        TicketListItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            priority: components["schemas"]["Priority"];
            /** Status */
            status: string | null;
            /** Needs Human Eyes */
            needs_human_eyes: boolean;
            /** Linear Url */
            linear_url: string | null;
            /** Project */
            project: string | null;
            /** Labels */
            labels: string[];
            /** Parent Id */
            parent_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TicketRef
         * @description Just enough of a ticket to render a link to it.
         */
        TicketRef: {
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** TimelineEntry */
        TimelineEntry: {
            /** Id */
            id: number;
            kind: components["schemas"]["TimelineKind"];
            actor: components["schemas"]["Actor"];
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string | null;
            /** Reason */
            reason: string | null;
        };
        /**
         * TimelineKind
         * @enum {string}
         */
        TimelineKind: "comment" | "status_change" | "flag_change" | "field_change";
        /** TicketCreate */
        TicketCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /** @default none */
            priority?: components["schemas"]["Priority"];
            /** Linear Url */
            linear_url?: string | null;
            /** Project */
            project?: string | null;
            /**
             * Labels
             * @default []
             */
            labels?: string[];
            /** Parent Id */
            parent_id?: number | null;
            /** Actor Session Id */
            actor_session_id: string;
        };
        /**
         * SortField
         * @enum {string}
         */
        SortField: "created_at" | "updated_at" | "priority";
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** TicketsSummary */
        TicketsSummary: {
            /** Needs Human Eyes Count */
            needs_human_eyes_count: number;
        };
        /**
         * TicketPatch
         * @description A4: per-key replace; omitted keys are untouched. Only ``project`` and
         *     ``linear_url`` may be cleared with an explicit ``null``.
         */
        TicketPatch: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            priority?: components["schemas"]["Priority"] | null;
            /** Linear Url */
            linear_url?: string | null;
            /** Project */
            project?: string | null;
            /** Labels */
            labels?: string[] | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Actor Session Id */
            actor_session_id: string;
        };
        /** StatusChangeIn */
        StatusChangeIn: {
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Actor Session Id */
            actor_session_id: string;
        };
        /** CommentIn */
        CommentIn: {
            /** Body */
            body: string;
            /** Actor Session Id */
            actor_session_id: string;
        };
        /** NeedsHumanEyesIn */
        NeedsHumanEyesIn: {
            /** Value */
            value: boolean;
            /** Reason */
            reason?: string | null;
            /** Actor Session Id */
            actor_session_id: string;
        };
        /** TaskDetail */
        TaskDetail: {
            /** Id */
            id: number;
            /** Ticket Id */
            ticket_id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            state: components["schemas"]["TaskState"];
            /** Depends On */
            depends_on: number[];
            /** Blocked By */
            blocked_by: number[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** History */
            history: components["schemas"]["TaskHistoryEntry"][];
        };
        /** TaskHistoryEntry */
        TaskHistoryEntry: {
            /** Id */
            id: number;
            kind: components["schemas"]["TaskHistoryKind"];
            actor: components["schemas"]["Actor"];
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            from_state: components["schemas"]["TaskState"] | null;
            to_state: components["schemas"]["TaskState"] | null;
            /** Reason */
            reason: string | null;
        };
        /**
         * TaskHistoryKind
         * @enum {string}
         */
        TaskHistoryKind: "state_change" | "field_change";
        /** TaskCreate */
        TaskCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Depends On
             * @default []
             */
            depends_on?: number[];
            /** Actor Session Id */
            actor_session_id: string;
        };
        /** Session */
        Session: {
            /** Session Id */
            session_id: string;
            /** Name */
            name: string;
            /** Directory */
            directory: string;
            /** Last Message */
            last_message: string | null;
            /** Last Message At */
            last_message_at: string | null;
            /** Ticket Id */
            ticket_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionIn */
        SessionIn: {
            /** Directory */
            directory: string;
            /** Last Message */
            last_message?: string | null;
            /** Last Message At */
            last_message_at?: string | null;
            /** Ticket Id */
            ticket_id?: number | null;
        };
        /** StatusItem */
        StatusItem: {
            /** Name */
            name: string;
            /** Is Builtin */
            is_builtin: boolean;
        };
        /**
         * TaskPatch
         * @description Per-key replace, like ``TicketPatch``. No task field is nullable, so an explicit
         *     ``null`` on any of them is rejected.
         */
        TaskPatch: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Depends On */
            depends_on?: number[] | null;
            /** Actor Session Id */
            actor_session_id: string;
        };
        /** TaskStateIn */
        TaskStateIn: {
            state: components["schemas"]["TaskState"];
            /** Reason */
            reason?: string | null;
            /** Actor Session Id */
            actor_session_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    tracker_api_tickets_list_tickets: {
        parameters: {
            query?: {
                sort?: "created_at" | "updated_at" | "priority";
                order?: "asc" | "desc";
                needs_human_eyes?: boolean | null;
                status?: string[];
                parent?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListItem"][];
                };
            };
        };
    };
    tracker_api_tickets_create_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
        };
    };
    tracker_api_tickets_tickets_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketsSummary"];
                };
            };
        };
    };
    tracker_api_tickets_get_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
        };
    };
    tracker_api_tickets_patch_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
        };
    };
    tracker_api_tickets_set_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
        };
    };
    tracker_api_tickets_add_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
        };
    };
    tracker_api_tickets_set_needs_human_eyes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NeedsHumanEyesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
        };
    };
    tracker_api_tickets_list_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    tracker_api_tickets_create_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
        };
    };
    tracker_api_sessions_register_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    tracker_api_sessions_list_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    tracker_api_statuses_list_statuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusItem"][];
                };
            };
        };
    };
    tracker_api_tasks_get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
        };
    };
    tracker_api_tasks_patch_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
        };
    };
    tracker_api_tasks_set_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
        };
    };
}
